language: ruby
script: bundle exec rspec
rvm:
- 2.7.0
deploy:
  provider: heroku
  api_key:
    secure: nLDNTRccGHilUI9ryZo5i1LvFC1e7PmSuZovl2h+FrqjfnJnS9cZEElaqWGv6YlEMFJBNJR9wEeWe1xvRLtUgQujsQgwD9F53wD2ZjaGKfQJWzlcKFEEjmvVSwKo7a7S+hxm7+ZDGmE/eH/w/0GL59xzo41KjUkbgFDqiz2jbcWfQNq/bS4+HY1mEKWkf+jW6bjRxw44ou2fB1E8xV6bLoTEMNHj6n135xhUbTDwETRVzZ5hcy4ug9THeN4w0BQh9WgiVA+w9lqhKqUQKOgzJMHW8cFDFuFx8c0XNjvlnJJvhcf1HHV9DxoZ+gkFVmwV/XFYqB0avNldYb3E/AaB+NcXjCd8kix6rK/i3nJqYCVu++cSRqqTGQUdskBngRaDhKpjJjk3jQOhDnGQrJZ0NAXtYwqj3+FkhQ0W9L0HbW9IprPVMvot2QJepCBPRd4jnBfEI/z+KyPFT2M2Ag6bsS2LuT0lV8rlpvcPcsZs5Nsf/pf+1Ai0B2ebhIBetZm3TIWd+hVE0ZntjB4Ra+9My814GCnktoKqaiL5VH83ZeSzdVkxDxkYHCctVyd75P2LCjbwxuxUaVobbhHqqHVbjMCRDnDiQyhDHzUw5UDX9wvYzJBfJlkOHyyxIfjrfWsfOeslQw9i9k1vVomlnGIshA8KOYMz2vHhie69iqcwIAg=
before_install:
- gem install bundler
