language: ruby
script: bundle exec rspec
rvm:
- 2.7.0
deploy:
  provider: heroku
  api_key:
    secure: D9oNAzd/IhvVp2ES5JCX7gocO4YhsQ3WsRTGhy9x9Cd/rR5FOfXLqizAO6OLQzAaGKyDH/YcF20ca3v83t8iMgEZgWVPYthnkMYXoChzKtyKVweQOS++UCqDem7cx5Qe4FCbr1/97GwjssgnDAm7cfMUmyOHVyW5z0QNs07SkH7ICvSf/A9X/aByAz2fXaxsAx+1b4YlHEqqbnGDEkp+uvz7DidWJ5FWFO3+xxiwE9UvQnaiSJBVnvJ4SCsrfSphYDtGt5RFdpC0ReXFigK6g3ABJ07Mtnxu/XZ5ow9fEn6noSYEaGSxAXGML9vHyEgI0v1r/hp/hxoYBhBE7M+GlYLIUhT87VQLZzJ3n4pziGUyunlLRj/qxfe28b8EuFywqfCBownI0E7xd42ODK7RXI2OSZT0fL+qMmlieYfdXtMsJxdmTiqsEJOi5faiKNIlJdI97yByVXfnJB3jJt9lRjdvDxoFk9tBdq9WqjgJxRPWV964CIp3U2rVT1zIQnINtMpvY6LrYlq3SlAD7xBLQ4hkLbtsQub8adRZO8mXzyA+rV6zBTh2b6+Ivp4dGVnuwSyvDeAQikqa7VYVS7EnJvphd2M+ZBSoe5uVfEay7iPJLxEgaVXAVs9270SP5OC6OQF7RYNueVPrfo7AnVWoUT6P8JFY5E8xZecGXUlcPz0=
  run: "rackup -p 4567"
before_install:
- gem install bundler
